spring:
  ai:
    openai:
      api-key: ${AI_TOKEN}
      chat:
        options:
          model: deepseek-chat
      base-url: ${AI_URL:http://api.deepseek.com}
      embedding:
        enabled: false
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${PG_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
