spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${PG_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
deepseek:
  api:
    url: ${AI_URL:http://api.deepseek.com}
    key: ${AI_TOKEN}
